# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  buildNumber: '$(Build.BuildId)'
  docker.registry.public: docker.io
  docker.image: uanid/simple-file-server

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Jar_Build_Stage
    displayName: Build Jar Stage
    jobs:
      - job: Jar_Build_Job
        displayName: Build Jar Job
        container:
          image: maven:3.3-jdk-8
        steps:
          - script: |
              mvn package
          - publish: target/
            artifact: MyApp
  - stage: Docker_Build_Stage
    displayName: Docker Image Build
    jobs:
      - job: Docker_Build_Job
        displayName: Docker Image Build
        container:
          image: gitlab/dind:latest
        steps:
          - download: current
            artifact: MyApp
            patterns: "*.jar"
          - script: |
              mkdir target/
              cp ../MyApp/*.jar target/
              docker build -t $(docker.image):$(buildNumber) -t uanid/simple-file-server:latest .
              docker login -u $(docker.username) -p $(docker.password) $(docker.registry.public)
              docker images
              docker push uanid/simple-file-server:latest